# Generated by Django 5.1.5 on 2025-02-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GT_Movies_Store', '0002_alter_movie_release_date_alter_movie_title'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='MovieStore_movie',
        ),
    ]
