# Generated by Django 5.1.5 on 2025-02-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GT_Movies_Store', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images/'),
        ),
    ]
